import React from 'react';
import { authenticationService } from '@/_services';
import io from "socket.io-client";
import Flat from "./flat";
import Suwak from "./suwak";

class HomePage extends React.Component {
    constructor(props) {
        super(props);
        this.handleSwitchChange = this.handleSwitchChange.bind(this);
        this.state = {
            currentUser: authenticationService.currentUserValue,
            switchValue: {
              room: 0,
              hall: 0,
              bedroom: 0, 
              kitchen: 0,
              bathroom: 0
            },
            switchesNames: [],
            lastEvents: []

        };
        this.socket = io.connect('http://localhost:3030', {
            query: {token: authenticationService.currentUserValue.token}
          });
    }

    componentDidMount() {
        // update state from of switch with socket data
        this.socket.on("update-switch", data => this.handleSwitchChange(data[0])(data[1]));

        // sets states of swiches after new connection to socket
        this.socket.on("hello", data => data.forEach(element => {
          this.handleSwitchChange(element.name)(element.state.value)
        }));

        // array for autogenerated list of swiches 
        this.state.switchesNames = Object.keys(this.state.switchValue)
    }

      handleSwitchChange = name => value => {
        const { switchValue: switchValue } = this.state;
        console.log("updating value", name, value);
        this.setState({
          switchValue: {
            ...switchValue,
            [name]: value
          }
        });
      };


    render() {
        const {currentUser, switchesNames} = this.state;
        return (
            <div>
                <h5>Zalogowany: <b>{currentUser.firstName}</b></h5>
                {/* <h8>JWT: {currentUser.token}</h8> */}

                {switchesNames.map(n => (
                  <Suwak
                    value={this.state.switchValue[n]}
                    onSwitchChange={this.handleSwitchChange(n)}
                    name={n}
                    socket={this.socket}
                    permission={currentUser.permission_policy[n]}
                  />
                ))}
                 
                <Flat 
                  room={`rgba( 255, 255, 255, ${this.state.switchValue.room/255} )`} 
                  hall={`rgba( 255, 255, 255, ${this.state.switchValue.hall/255} )`} 
                  bedroom={`rgba( 255, 255, 255, ${this.state.switchValue.bedroom/255} )`}
                  kitchen={`rgba( 255, 255, 255, ${this.state.switchValue.kitchen/255} )`} 
                  bathroom={`rgba( 255, 255, 255, ${this.state.switchValue.bathroom/255} )`}
                  balcony="gray"
                  displayText={true}
                />
            </div>
        );
    }
}
export { HomePage };